// app/layout.tsx
import "./globals.css";
import type { Metadata } from "next";
import { SessionProvider } from "@/lib/SessionContext";
import ClientWrapper from "@/components/ClientWrapper";
import GlobalSettingsProvider from "@/contexts/GlobalSettingsContext";

export const metadata: Metadata = {
  title: "Galuxium",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased ">
        <SessionProvider>
          <GlobalSettingsProvider>
         
      
              <ClientWrapper>{children}</ClientWrapper>
           
          </GlobalSettingsProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
